void print_line(String text, int column, int row, int text_size)
void print_time_now(void)
void update_time()
void ring_alarm()
void update_time_with_check_alarm(void)
int wait_for_button_press()
void go_to_menu(void)
void set_time()
void set_alarm(int alarm)
void run_mode(int mode)
void check_temp()

void buzzerOn(bool on)
void setupMqtt()
void receiveCallback(char* topic, byte* payload, unsigned int length)
void connectToBroker()
void updateTemperature()
void updateIntensity()
void adjustWindow()
void setupWifi()
unsigned long getTime()
void checkSchedule()